### ISSUE TITLE
Ignore spaces when you type in "123 456" instead of "123456"

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/twofactor_totp#189]

**Comment by My1** [comment]
where exactly does the verification happen? wouldnt be hard to insert a preg_replace or something around that thing right before validating the totp.

technically I would grab the verify function and throw in a nice
~~~php
$otp=preg_replace("/[^0-9]/","",$otp);
~~~

another way of doing it would be just axing the characters on js level, but I think that if it can be done on the server, it should be.

**Comment by ChristophWurst** [comment]
> where exactly does the verification happen?

https://github.com/nextcloud/twofactor_totp/blob/2cd10802c2e91788a685249105a37054437d98b7/lib/Provider/TotpProvider.php#L91

> another way of doing it would be just axing the characters on js level

Agreed.

**Comment by My1** [comment]
but doesnt challenge sound kinda weird in this context, after all from a classic challenge-response model, the time would be the challenge and the OTP the response.

no wonder I didnt find this (also since I kept looking for the OTP calculation, which involves HMAC and the truncation. (I recently exchanged an ugly OTP library from a tutorial with one I made on my own (it had a function which could create a random secret but used `rand()`, lol))

honestly it's too bad I cant just run nc on windows, testing this would have been a breeze,but guess, I set up another instance at a server, anyway, sooner or later you're gonna hear from me.

**Comment by My1** [comment]
well stuff went quick and here's my result:
throwing in
~~~php
$challenge=preg_replace('/[^0-9]/','',$challenge);
~~~
right after that line certainly helps resolving the server side, although we first also need to increase the maxlength on the field otherwise any spaces and stuff would obviously go against the limit either and the final numbers wont make it.

also while JS certainly is another option to fix this I personally prefer "never trust the client's input" and also, TOTP would be able to integrate into client applications, where you cant play around with some JS.

**Comment by My1** [comment]
so. #203 should fix this.
