### ISSUE TITLE
Feature request: Add option to 'Trust this device'

### ISSUE THREAD

**Issue by catuan** [nextcloud/twofactor_totp#192]
When logging in with 2FA it would be great to have a checkbox giving the option to "Trust this device". Subsequent logins from the same browser should allow the user to log in using only their password. Any logins not from a "trusted device" should still require a second authentication factor.

The user should also be able to revoke sessions from "trusted devices" (like any other logged in session). When this happens, the device should no longer be considered trusted and should require 2FA on the next login.

You should also be able to choose "Trust this device" when logging in using backup codes.

Rationale: 

I think this feature would make 2FA more user friendly, not requiring them to enter their 2FA codes every time they log in. But still making it much more difficult for attackers to break into an account.

Implementation details:

I don't have a lot of web development experience. But I believe that a unique, randomly generated value stored in a "persistent" cookie would be the easiest way to implement such a feature. The cookie should be kept by the browser even after the user logs out. When logging back in, Nextcloud should recognize the cookie and only require the user to enter their password.

**Comment by ChristophWurst** [comment]
Hey @catuan,

thanks a lot for this detailed feature request. Actually, we already have a ticket for this here: https://github.com/nextcloud/server/issues/2906. It's in the server repo because this is a generic feature that should be available for all 2FA providers and not just TOTP.
Could you please copy-paste your feedback to the other ticket? That would be awesome.

Thanks a lot!
