### ISSUE TITLE
Possible Denial of Service when TOTP was not fully configured

### ISSUE THREAD

**Issue by kmonticolo** [nextcloud/twofactor_totp#214]
Hello,
I figured out, that is possible to lock down account by check "Activate TOTP" button and simply logout without passing token code.

To reproduce:
Create new user, sign as new user, check "Activate TOTP" button and logout. The user will be not able to log in again due to lack of TOTP code.
Tested on:
OpenBSD 6.2
OwnCloud version 10.0.3.3
Two Factor TOTP Provider 0.4.3

**Comment by ChristophWurst** [comment]
Hi,

first of all thanks for your report. While it is correct that OwnCloud's TOTP plugin does not prevent this kind of lock-out, this does not apply to the Nextcloud TOTP app (which you've submitted the bug report to). This problem has been fixed for Nextcloud a couple of months back.

I'm closing this now since you're not using Nextcloud and the problem has been addresses here already.
