### ISSUE TITLE
Security vulnerability: Replay attacks

### ISSUE THREAD

**Issue by sindastra** [nextcloud/twofactor_totp#245]
# What happens:
It is possible to reuse a generated code.

# What's supposed to happen:
The application should temporarily store the code on the server side, to disallow reusing the code (replay attack).

# How to reproduce:
Sign in, enter the TOTP code, sign out and sign back in and enter the same TOTP code (within the ~30 seconds validity).

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/twofactor_totp/issues/100

**Comment by sindastra** [comment]
#100 seems pretty dead so I'm reopening this for now.

**Comment by tessus** [comment]
The flow could be as follows:

1. at login hash current token, check if hash exists in table `X` for user `Y` in certain time period
1.1 if yes, return error message (e.g.: `Token reused, please try again in Ns.`) [1]
1.2 if no, insert/update hash and timestamp in table `X` for userid `Y`

 [1] We can determine the period and how many more seconds N someone would have to wait for a new token.

**Comment by sindastra** [comment]
Why hash the token? It’s just six digits and can be figured out with a rainbow table and only exists for about 30 - 60 seconds. If you’d want to protect it you’d have to salt it, but that makes no sense as the “secret key” itself is, as far as I know, stored unencrypted. Or am I missing the point of hashing the token?

From my understanding, it can be stored as plain text for 30-60 seconds and then deleted again, as the point is to just avoid replay attacks.

Besides, if someone has access to the database they’ll get a token that cannot be used, and they could get the secret key generate valid tokens anyway.

If I’m missing something, please elaborate, thanks!

PS If it’s not needed security wise, we shouldn’t add more operations because of performance, especially for large instances.

**Comment by tessus** [comment]
Nope, you are right. Hashing of the token is not necessary. I only thought of it as 'just-in-case' and that we don't put any plain text in the db. But as you correctly pointed out it's invalid anyway.

**Comment by ChristophWurst** [comment]
Thank you for your input, @tessus @sindastra! Could you please move this discussion to https://github.com/nextcloud/twofactor_totp/issues/100?

**Comment by sindastra** [comment]
I just tested it again on Nextcloud 14.0.6 with Two Factor TOTP Provider 1.5.0 and replay attacks still work.

So this hasn't been resolved yet. JFYI.

**Comment by Heracles31** [comment]
Hi,
I confirmed here : TOTP is still vulnerable to replay attack. Here, I logged once from a first computer and a second time from a second computer with the same not-so-one-time code.

To prevent replay attack is the main reason for a OTP, so to be vulnerable to replay is a big problem...

**Comment by tessus** [comment]
Maybe @ChristophWurst can tell me where in the code I can add the following flow:

1. at login, check if hash exists in table `X` for user `Y` in certain time period
1.1 if yes, return error message (e.g.: `Token reused, please try again in Ns.`) [1]
1.2 if no, insert/update hash and timestamp in table `X` for userid `Y`

I'd also need to know, how to add an additional table `X` to the nextcloud database. I'm not a nextcloud app dev, so I need some pointers here.

For an app dev this entire thing shouldn't take longer than 5 minutes to implement. Not quite sure why it hasn't been done yet. @ChristophWurst do you disagree that this is a security issue and don't you want to have this resolved? I'm just asking, because I'm not going to waste hours of my time to try figuring all this code out and then the change won't even be merged.

**Comment by Heracles31** [comment]
Hi Tessus,

Thanks for offering to fix that.

Considering the OTP will now be one time, I do not think it is important to hide it by hashing it. Once used, it turns to unusable, so it has no value. Also, I think the check can be even easier then what you described.

When a user log with a TOTP, first thing is to check if the code is the proper one for this moment in time (already done as of now of course...)
If it is, look in the database to see what was the last successful TOTP code used by that account, if any (the user may not have log with TOTP yet or at least, not since this new control have been implemented).
If it is the same, reject the login and ask to retry in 30 seconds with another code.
If it is different (or no previous code), grant the access and update the last successful TOTP code with the new one.

The timestamp you proposed would help only in case of a collision, a case where the same TOTP code is generated twice in a row and to be used legitimately twice. The randomness of the TOTP is enough to rely such a case will not happen and should I ever be wrong, the only consequence is asking the guy for 30 seconds for him to get another code.

As for the importance of making a OTP one time, it is 100% of the purpose of the code that relies on that. Static passwords can be recovered in many ways and this is what make them weak. The idea behind TOTP is that should a TOTP code be recovered in the same way a static password have been recovered, it will not be re-usable in any way.

I saw that in the past, people compared the risk of TOTP replay to the one of hijacking a cookie. That is limited to the case of a network interception. Also, as pointed out by others, the regular interaction with a web session will kill that cookie while a separate session opened with a stolen TOTP code can stay open for vert long.

The one-time aspect of TOTP is the protection against key loggers, against people looking at you when you enter your code and more.
It also mitigates risks like copying session cookie by ensuring the illicit session will be terminated as soon as the main one itself is closed. So should one need to use a public computer, he is safe as soon as he log out of his session. A cookie is less valuable than a valid TOTP code.

So definitely, I think the app should be a TOTP, a Time-based ONE-TIME Password and not just a TP, a Time-based Password.

Regards,

**Comment by tessus** [comment]
I agree, the hash is still a leftover from a copy and paste operation. We've already established in previous comments that hashes are unnecessary in this case.

I understand the importance of hardening the code against replay attacks, I'm just wondering why the author hasn't fixed it yet. - especially since it basically renders TOTP null and void (well on the other hand one would have to crack the TLS connection first, which is rather hard with forward secrecy).

As I mentioned before, I could use some help since I am not a nextcloud app dev. I hope @ChristophWurst can either drop me an email and/or act as a mentor.

**Comment by tessus** [comment]
P.S.: If your system is compromised by a keylogger, your nextcloud account will be the least of your problems.

**Comment by Heracles31** [comment]
Considering I put everything in my Nextcloud, to preserve my Nextcloud from such an attack would really mean something to me :-)

The key logger illustrates the risk of a public computer. So see it as an access from a public computer instead of a local key logger on a private computer :-)

In all cases, thanks for your replies,

**Comment by tessus** [comment]
>Considering I put everything in my Nextcloud, to preserve my Nextcloud from such an attack would really mean something to me :-)

I'm not saying that data in nextcloud is not worth securing, I just wanted to convey that you would have a much bigger problem than just that.

>The key logger illustrates the risk of a public computer. So see it as an access from a public computer instead of a local key logger on a private computer :-)

Ah, I see. You are saying someone would access the keylogger remotely and would login within the 30s timeframe. Otherwise they can log the TOTP code and won't be able to use it later anyway. Usually keyloggers send data to a controller box where the data is stored for later analysis. You are already talking about a realtime reaction to a logger action. Wow, paranoid much? ;-) No, I see your point. You can't be safe enough these days.

 I really hope I get some feedback from the dev.

**Comment by sindastra** [comment]
TOTP has "one time" in the name, it's already established that it should be one time, so we shouldn't argue on whether this makes sense or not (it does). ;)

Someone just needs to implement the missing check to fix this.

PS It's ridiculous that no one bothered to fix a *security issue* for so long.

**Comment by ChristophWurst** [comment]
We are working on it.

**Comment by tessus** [comment]
Thank you for the info.

**Comment by WeihanLi** [comment]
Is there a solution here?

**Comment by tessus** [comment]
@WeihanLi not yet, but the devs are working on one.

**Comment by WeihanLi** [comment]
@tessus  ok, thanks for your reply

**Comment by rullzer** [comment]
Done with https://github.com/nextcloud/twofactor_totp/pull/489
