### ISSUE TITLE
Support for php7.1

### ISSUE THREAD

**Issue by a36233** [nextcloud/twofactor_totp#88]
I'm currently using php7.1 with apache and I cannot enable/install TOTP app because of the php maximum version is set to 7.0.
"This app cannot be installed because the following dependencies are not fulfilled:
PHP with a version lower than 7.0 is required."

**Comment by ChristophWurst** [comment]
Hi,
I've set it to php <= 7.0 simply because I did not yet get the chance to test it with php7.1. Once I'm confident that it's compatible I will of course explicitly allow the app to be used with php 7.1. In the meantime, you can test compatibility by manually tweaking the app's meta data in https://github.com/nextcloud/twofactor_totp/blob/f061926cce13c04e5119e09770d9cf8801a1e45b/appinfo/info.xml#L20.
Let me know if something breaks :-)

**Comment by ChristophWurst** [comment]
Just read that '7.0.13' is actually the latest stable version right now, so I will wait until it's officially released

**Comment by ChristophWurst** [comment]
The first step will be to enable 7.1 on travis once it's available: https://docs.travis-ci.com/user/languages/php/#Choosing-PHP-versions-to-test-against

**Comment by a36233** [comment]
Yes I'm using the dev version of PHP (7.1.0-1), I've manually tweaked the app's meta data and now TOTP and U2F are working normally.

**Comment by MariusBluem** [comment]
PHP 7.1 working with twofactor_totp for me too ... should be updated **before** the 11 release 🤔 @ChristophWurst

**Comment by ChristophWurst** [comment]
fixed by https://github.com/nextcloud/twofactor_totp/pull/99 🚀

**Comment by ChristophWurst** [comment]
php7.1 support can be tested with the latest nightly on https://apps.nextcloud.com/apps/twofactor_totp. @a36233 @MariusBluem feel free to submit your rating of you like the app 🌟
