### ISSUE TITLE
Buttons / Arrows in TOTP

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/twofactor_totp#93]
Since https://github.com/nextcloud/server/pull/1641 brought back the "Log In" button, I think we should overthink the buttons and arrows in TOTP too ... even if I am not a big fan of this decision I am a big fan of uniformity ... So ... Lets remove this arrow from TOTP and replace it with an dedicated button 😉 

@jancborchardt @ChristophWurst @nextcloud/designers

**Comment by jancborchardt** [comment]
@MariusBluem can you add screenshots for clarification? :)

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/twofactor_totp/blob/master/screenshots/enter_challenge.png

**Comment by ChristophWurst** [comment]
Was changed with https://github.com/nextcloud/twofactor_totp/pull/48. 

And we use that styling in the backup codes app too, which is part of NC11…

**Comment by My1** [comment]
uniformity aside, I honestly prefer buttons rather than that arrow, because it's more direct.

**Comment by Dennis1993** [comment]
Where I can see the change?
If I use Microsoft Edge, the arrow to submit the PIN is covered by the X from Edge itself.

![edge](https://cloud.githubusercontent.com/assets/1473674/23760728/e260cf46-04f0-11e7-971f-caf740f4cb38.PNG)

The Edge is displaying in each input the X to remove the written text. Maybe we use a button or can remove the X with the following Code:

```
input[type=text]::-ms-clear {
    display: none;
}
```

Maybe it is fixed with #48 I don't know :D Then sorry for my post :)

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/twofactor_totp/pull/149, forgot to close this ticket :-)
